name: Go Build and Test

on: [push]

jobs:
  go-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Setup Go {}
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Install Dependencies
        run: go get .
      - name: Build Go module
        run: go build -v ./...
      - name: Run Tests
        run: go test ./...
